### ISSUE TITLE
Gender Analysis: Request for Global GBV QA Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/Engagements#35]
GBV QA Request
--
### Summary Info and Dates:
**Submitted by**:       Meagan Cain 	 
**Approval Status**:   Approved
**Technical Area(s)**:   Data Visualization; DREAMS; Gender & Adolescent Girls; OVC; Pediatrics & Adolescents 	 
**Preferred Date Request is Completed By**:	1/1/2019 	 	 	 
**Type of Engagement**: Virtual Support 	 

**Dates:**

- Submitted 9/26
- Confirmed receipt 9/28
- Reviewed by leads: 10/1 (decision not made)
- Re-reviewed by leads 10/15
- Approved 10/15 with caveats
- Email sent with approval on 10/17

Engagement Request
--
**Who**:	
Global. Initial OUs will include Nigeria, Kenya, Uganda, South Africa 	 

**What**:	
This request is to create a “Global GBV QA Tool Dashboard” to visualize and share site-level data from OUs implementing the GBV QA Tool. This global and flexible dashboard will allow users to produce simple displays of how well OUs are achieving across the 28 standards of quality post-violence care over time, as outlined in the GBV QA Tool. In addition to the full 28 standard tool, the Dashboard will also allow users to specifically compile data related to the standards that represent the PEPFAR minimum package of post-violence care.  	 

**Why**: 
This global dashboard will allow OUs to not only assess themselves and identify gaps related quality within their own GBV programs but will also allow them to look at other OUs data scores for cross learning and friendly comparisons. We envision that common gaps will give more direction to specific TA needs while also creating opportunities for advocacy for specific services/standards. 

Achievements of specific standards will allow for recognition of program successes and opportunities to pursue lessons learned for other OUs. While MER guidance outlines specific services that must be in place to count under the GEN_GBV indicator (i.e. minimum package), there is no routine monitoring or assessment of this minimum package was in place or not. 

This Dashboard fills an important gap not currently fully assessed by SIMS in that it will allow us to monitor if the minimum package is actually being in place for accurate MER indicator (GEN_GBV) reporting.  	 

**How**: 
This Dashboard will need to be designed based off of the GBV QA Tool’s standards (28). Each standard is based off of a number of verification criteria and all of the verification criteria must be met to consider a standard “achieved.” In addition to displaying the number of standards met, the Dashboard should allow a user to dig deeper into the data and locate which specific verification criteria was met or not met for the purpose of program improvement. The Dashboard will be populated from datasets submitted by the OU from each assessment (submitted within 2 weeks of assessment).  	 

**Source of Request:**	This request comes concurrently with the timing of the GBV QA Tool rollout across a number of PEPFAR OUs. Two Regional Assessor Trainings in Uganda and South Africa brought together field and HQ staff from across PEPFAR to introduce the tool and provide momentum for moving the Tool implementation forward. As OUs begin to formulate plans for rollout and commit to quality GBV services, there is a recognized need to track and visualize progress in addressing gaps and strengths from the QA assessments. 

This Dashboard, to be used and available across agencies, will allow more meaningful use of data collected. To ensure accountability in QA efforts, country teams and HQ will be involved in the development and upkeep of the Dashboards.  	 

**Specific Deliverables**: 
The main deliverable of the GBV QA Dashboard will require the following: 
- Translation of the tool standards and verification criteria scoring into visual displays 
- Creation of pivot tables that display key elements, such as # of sites assessed, Scores for the overall tool, scores for the minimum criteria and % of sites meeting the standards and having minimum packages in place. A separate pivot table should allow the user to see why a criteria was or was not met due to achievement (yes/no) for each verification criteria. 
- Data entry platforms for OUs to enter data from their scoring sheets (collected by paper or device) and minimum package in placement assessment. 
- data deduplications and cleaning criterions 

 	 
**Intended Audience**:	PEPFAR HQ Teams and country teams, including GBV/gender staff. Additionally, these displays may be shared with MOHs to advocate for services or showcase effectiveness. 	 

**Outbrief and Communication Plan**:	Communication on progress will be communicated via regular ICPI calls with key HQ POCs (CDC, USAID, DOD) and country colleagues from GBV QA implementing OUs. 
Upon finalization of the dashboard, there will be an interagency out brief webinar to disseminate the dashboard and train on its use. Additionally, HQ Teams will incorporate the training and purpose of the dashboard into the wider GBV QA Tool training curriculum for OUs implementing the tool. 
 	 
**Others Involved in Request**: CDC: Jennifer Hegle, Carol Lin, Jennifer Drummond, Adeola Ayo (Nigeria), Mary Mwangi (Kenya), Sibongile Dladla (South Africa), Rose Apondi (Uganda) 
USAID: Amelia Peltz, Emily Reitenauer 
 	 
SharePoint Resources Here
--
Information on [SharePoint  ICPI > Clusters > Prevention > Projects > GBV QA](https://www.pepfar.net/OGAC-HQ/icpi/SharedDocuments/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FProjects%2FGBV%20QA&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
# **GBV QA Project Overview**

## QBV QA Tool Dashboard

Last updated October 17, 2018

## **Project Overview**

The Prevention Cluster has been asked to develop a tool that country teams can use to analyze and visualize the data collected from the Gender-based Violence Quality Assurance (GBV QA) Tool, developed by CDC and Jhpiego and adopted by the WHO, is used to assess, improve, and ensure the quality of post-violence health services.

For more information on the tool, the following resources are in the prevention cluster folder:

- GBV QA Tool
- GBV QA Tool - Minimum Standards _(this version of the tool should only be used in resource-limited site and sites just standing up their post-violence clinical care services)_
- GBV QA Tool Facilitation Guide
- GBV QA Tool Score Sheet _(an Excel sheet that assessors use to score sites when using the GBV QA Tool)_
- Slide deck used during the GBV QA Tool regional trainings

## **Webinar Link**

GBV QA Tool Webinar on Youtube

[https://www.youtube.com/watch?v=SACFcmwCm5I&amp;feature=youtu.be](https://www.youtube.com/watch?v=SACFcmwCm5I&amp;feature=youtu.be)



## **ICPI Leads Approval Status**

APPROVED: Leads approved the engagement request on 10/15/18

Specific Questions sent via email on 10/17,

Email subject : &quot;APPROVED: Engagement &quot;Global GBV QA Dashboard&quot; -  Meagan Cain&quot;

**ICPI Leads Response to Specific Deliverables** :

- **Deliverable 1** : Data entry platforms for OUs to enter data from their scoring sheets (collected by paper or device) and minimum package in placement assessment.
  - **Response** : was this a part of the original protocol? If so, kindly summarize and send the language
  - ICPI can create an excel template and a process, but does not have the mandate to build a &quot;platform&quot; like DATIM
    - An ICPI output can be an excel template that country teams can use to enter their data into
    - If the team would like a more formal platform, the ICPI can partner with the systems representatives in the PEPFAR interagency space to scope out requirements for a &quot;data collection platform&quot; and all of the data governance that goes along with a platform. We can explore having a team called, PISA look into building out an application in DATIM.
    - Given the timeline, it is unlikely that the PEPFAR systems team will have the bandwidth to accommodate adding in a data entry system for the GBVQA data.
    - **ICPI&#39;s recommendation** is to start with excel as part of the proof of concept OR work within one of the agency specific systems teams to develop a PEPFAR compliant platform for data collection and management
- **Deliverable 2** : Requirements for data deduplication and cleaning criteria
  - **Response** : To reiterate the question above, if the protocol submitted discusses data collection methods, we can start there and build out the implementation and translation pieces
  - If this information does not exist, then as part of the methods and requirements portion of the project, these sections will certainly include this information
    - The methods will need to include a data lifecycle overview from data collection, data management, cleaning, storage, submission, consolidation, visualization, and maintenance.
    - The requirements for each of these components will also need to be outlined
- **Deliverable 3:  ** Creation of pivot tables that display key elements, such as # of sites assessed, Scores for the overall tool, scores for the minimum criteria and % of sites meeting the standards and having minimum packages in place. A separate pivot table should allow the user to see why a criteria was or was not met due to achievement (yes/no) for each verification criteria.
  - **Response** : Deliverables 3 and 4 are similar.
  - **Deliverable 3** : A consolidated dataset and tables upon which additional visualizations can be built
- **Deliverable 4:** Translation of the tool standards and verification criteria scoring into visual displays
  - **Response** : This is the final outcome of the project
  - An interactive excel dashboard that includes an overview of how to use the tool and its components
  - Tabs that visually display charts/pivots/etc that visually represent the information along with guiding questions and interpretations
  - This product will need to be cleared by ICPI leads. Please factor this into your &quot;release date&quot;. It will be considered part of the ICPI suite.
- **Deliverable 5:** Supporting the GBV QA team on training the country teams on the process
- **Deliverable 6:** Supporting the GBV QA team on using the data, sharing the results of the interpretations with the PEPFAR HQ/ICPI/ECT community on the impact of the data
- **Deliverable 7:** Sustainability plan – who will maintain and update the data as they come in? When will the project close?



**Next steps:**

- Review and respond to questions in the responses to the deliverables above
- Kimi and Erin to assign an analyst to manage the project (Jasmine can work with leads to do this if needed)
- Identify a timeline and confirm final outputs/deliverables
- CDC to confirm the protocol was submitted and will provide background on data collection approvals
- ICPI leads to identify appropriate collaborator for the systems piece – ICPI can advise and provide requirements, but will not be primary on creating a data collection system
- If needed, prevention cluster leads to collaborate with data collection systems POC once identified
- Prevention cluster leads to keep ICPI up to date on project progress via inbrief, GitHub, or other fora



## **Engagement Request Details**

- Information on GitHub [https://github.com/ICPI/Engagements/issues/35](https://github.com/ICPI/Engagements/issues/35)
- Information on SharePoint ICPI \&gt; Clusters \&gt; Prevention \&gt; Projects \&gt; GBV QA [click here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FProjects%2FGBV%20QA&amp;FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&amp;View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
- Summarized Above

**Comment by kkale25** [comment]
Hi all - @kimisatoPC @erinschelar @hessionra @jb3436 

Just checking in to see if there are any updates from the next steps for this request? It's been a while since we talked about it at Leads so making sure it didn't get dropped from our list!

**Comment by kkale25** [comment]
Just got an update from @jb3436 

Being reviewed by Leads next week (Anne and Catherine). Leads to provide feedback to Kimi/Erin.

**Comment by jb3436** [comment]
Product submitted for leads review. Comments provided in this ticket https://github.com/ICPI/Coordination/issues/47

**Comment by kkale25** [comment]
See ticket linked above for final product.
