### ISSUE TITLE
South Africa COP18 OPU targets retcon in site-level tools

### ISSUE THREAD

**Issue by wvp3** [ICPI/Engagements#80]
Task: support the reassignment of targets between implementing partners as agreed for the COP18 OPU, by revising site-level tools (site level normal and site level HTS tools) 

[SharePoint tools](https://www.pepfar.net/ou/southafrica/HQ%20Collaboration/Forms/AllItems.aspx?RootFolder=%2Fou%2Fsouthafrica%2FHQ%20Collaboration%2FCOP%202018%20%E2%80%93%20FY%202019%2FDatapack&FolderCTID=0x0120002EBEB387668FB04AB49607B828E1D04600D4EADCB03357C1499149664CDC5A310C&View=%7BFC8D18B8%2D9028%2D4FBB%2D9366%2D809A90ED8A80%7D)

- [x] Jason Pickering must add Travis, Aliyah, Yaa and Gina to the ticket so that we can view and download the most recent versions of the tools including updated mechanism names

9/30 - 10/7: Travis will take a first pass at revising the tools
10/7 - 10/11: Yaa and Gina will QC the changes and propose any fixes or revisions according to the OPU agreements

**Comment by aliyahwakil** [comment]
Initial QC:

 eThewkini: I started to review PMTCT and TB(ART STAT, PREV) and found the same pattern. 
•	The roll up to the district and IM level look okay for eThewkini but 100% of targets for kz Chatsworth Township Centre Clinic {Facility} (HD8l3wLgl0l) should be transferred to HST. It looks like the 25/75 was applied instead. 

 Tshwane:
•	indicators check out within rounding parameters with the exception of TB_PREV D which was split 25/75 between partners when it should be 100% with Aurum.
Cape Town:
•	I stopped after the first few indicators because they appear to follow the 25/75 split logic used in Tshwane for non-snapshot indicators, when it should use a 50/50 split.

**Comment by gsarfaty** [comment]
@wvp3 completed both the normal and HTS site tools, incorporating all QC feedback from @Yabayabadoo, @aliyahwakil and @gsarfaty, as well as changes to PP_PREV authorized by PPM. 

PPM will review & advise on next steps. 

ICPI team has outstanding Q's on how to address mechanisms that display differently in site tools vs. DATIM. Will check with J. Pickering.

**Comment by aliyahwakil** [comment]
Closing this ticket because tool has been submitted and approved by PPM
