### ISSUE TITLE
Botswana - PCO Infographic Request

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/Engagements#87]
Timeline: 
Request Received: 9/1
DIV team absorbed:  9/2 (with support from HSS cluster) 
Leads review on: 9/14 (9/07 was a holiday) 

Request
Engagement form send in by Sarah Klucking (OGAC chair 9/1) <KluckingSR@state.gov>

OU POC Name: Payne, John C <PayneJC@state.gov>; Browa, Sylvain (CDC state.gov) <browasa@state.gov>

Technical Area(s): TBD

Preferred Date Request is Completed By:  Mid October 

Type of Engagement: Virtual Support

Primary Requestor(s): Payne, John C <PayneJC@state.gov> (PEPFAR Coordinating Office) 

Summary of Request: We were wondering if ICPI is able, willing and available to assist us with simple reader-friendly info graphics to get the following information out:
1.      How much money the USG is committing to support Botswana's HIV/AIDS and TB programs in COP20/FY21?
2.      The health facilities and health districts these funds are supporting & in which ways (TA/HRH/Commodities)?
3.      Who are the implementing partners, how much money they receive to implement which activities?
4.      Which programs areas is COP20 supporting and for how many beneficiaries?

Objective of Request: In Botswana this year (FY21), PCO want to kick off COP20/FY21 with an outreach to the average citizen to inform him/her about how and the extent to which PEPFAR intends to support the country efforts to achieve HIV epidemic control

Specific Deliverables:  TBD

Title of Request: PCO/Botswana support for FY21 strategic communications 

Requestor Name: John Payne

HQ POC Name: Sarah Klucking

**Comment by Yabayabadoo** [comment]
Meeting with Country Team

Attendees: Jamie Houston, John Payne, Kate Wilkins, Randy Yee, Sylvain Browa, Yaa Obeng

Goal: Answer follow up questions, confirm timeline and clarify request

1)	What data sources should be used for this analysis? **Budget and MER data**
2)	How will the ICPI analysts collaborate with you  (e.g. will he determine which software should be used? The formats etc.?)  **Outputs should be easily readable by all. Software choice is not important, but the team plans to use the outputs on social media and print platforms (e.g. Facebook, Newspapers, etc.)**
3)	ICPI has never worked on tools for use beyond the PEPFAR sphere, are there any State Department (SGAC) processes we need to consider at HQ? (Assuming PCO will take care of it in country) **OGAC processes already planned, PCO will coordinate in country review and approval processes.**

Additional Notes:

PCO Botswana plans to roll out the media campaign in FY21 Q1. Preference is to receive support from ICPI, but will hire a contractor if needed.

 Decisions
1. Use available HRH data (FY19 Q4)
2. Budget and MER data will be sourced from Structured datasets
3. Country team can share DREAMS specific data
4. ICPI leads will discuss request Monday, 9/14
5. If approved, @KateWilkinsMPH @randyyee @Yabayabadoo will coordinate and complete analysis

**Request deadline: Week of October 12th**

**Comment by HoustonJamie** [comment]
Approved by leads on 9/16 @Yabayabadoo @randyyee @KateWilkinsMPH; no comments or concerns, adding @SchneiderMadeline as an FYI.

**Comment by randyyee** [comment]
Cross Cluster Collab (DIV & HSS) Kickoff Meeting

Attendees: Jamie Houston, Travis Lim, Kate Wilkins, Shazad Ahmed, Roma Bhakoti, Randy Yee, Yaa Obeng

Summary

1. HSS Cluster will focus on HRH/Commodities Data Points
2. Use MSD for data but QC against Spotlight for consistency
3. Jamie will reach out PET after Friday to request guidance on budget and expenditure datasets, QC etc.
4. Jamie will connect with David Heron from PEPFAR Comms
5. Next Steps: organize call with Bots Team, identify open source infographic platforms, assign POCs for each component
6. Bots Team Agenda should include: type of infographic, any formatting rules or mockups, request for DREAMS specific data that they promised last time

**Comment by randyyee** [comment]
Botswana Touchbase

Attendees: John, Sylvain, Jamie, Travis, Maddy, Kate, LaChandra, Randy

1.  Infographics

- ICPI Team will be free to make design decisions (viz type, etc) for infographics, will provide options for Botswana Team to review

- Suggestion to use free, open-source, easy-to-use infographic software for eventual handoff to Bots Team, ICPI still exploring options

2. Timeline

- John will be on leave until next Tuesday, can reach him after for any questions

- October 23rd deadline agreed

3. DREAMS Data Status

- Bots Team needs some time to prepare DREAMS data for this request, Sylvain will provide data by October 9th

4. Question Review

- John mentioned importance of providing context around infographics so that audience can see significance of PEPFAR's impact

- Question 2, DSD including in this analysis, Sylvain to provide an example for our reference (PPT, slide 4)

- Question 3, ICPI should have financial data available, but need to determine which is public, also need to resolve potential discrepancies between planning and data sources, may need to work closely with Bots Team on this

- John and Sylvain to provide list of partners and their areas of support for reference

- Pano Spotlight has examples of spend by program area (no IMs) but can go to Pano

5. Next Steps

- Will coordinate with DIV/HSS to prepare deliverables and set internal deadlines

**Comment by randyyee** [comment]
Kickoff

Software Options:
- Pictochart, Canva (newspaper potentially), Venngage, Adobe Spark, Design Tab, Mural, Google Charts, Infogram
- Yaa and Kate to explore further

HSS
- Question 2, LaChandra and Kate to explore current datasets to see if question can be answered and/or mockup a visual for now
- Potential contacts for HSS to support: Erin Rottinghaus, PET (Sally Blatz), Botswana

DIV + Shazad
- Will take on the remaining questions

Timeline
- Use the remainder of this week to reach out to contacts for any question about the data
- First draft to be completed on Oct 16th to be shared with Bots Team for feedback

**Comment by KateWilkinsMPH** [comment]
Hi All,

I'm trying to sort through all the emails with all the data in order to start a mock-up, and I'm having a hard time figuring out where we are with everything.

I think what might be best is if we all come together on Monday with the data we have, present, and then have a discussion about what we want the layout to be given the data on hand and the story it's telling. Also, if we can put our pivots/data in one spot, that would help, as well. 

I have availability all day after the In-Brief. 

Thanks,
Kate

**Comment by KateWilkinsMPH** [comment]
Hi All,

Here are my reviews and recommendations for infographics programs. @Yabayabadoo, thank you so much for doing the hard work of finding all these great programs. It was fun going through them to add my thoughts.

[WebbasedInfographics_KW Comments.docx](https://github.com/ICPI/Engagements/files/5394397/WebbasedInfographics_KW.Comments.docx)

**Comment by Yabayabadoo** [comment]
Meeting with PET Team 
Attendees: @randyyee @LaChandraS @KateWilkinsMPH @Leandra-stubbs @samstraitz @sallyblatz @Yabayabadoo 

Key Decisions:
PET team to compile all financial related data points:      
- [ ] Total COP 20 Budget
- [ ] COP20 Budget for Care & Treatment and Testing
- [ ] # of Mechanisms by contributing to Care & Treatment and testing
- [ ] COP20 Budget by DSD & TA

ICPI team to compile all MER related data points*:
- [ ] Counts of HRH 
- [ ] Counts of Facilities/Health Districts Supported (F/up with SGAC Data Management: @oharasl @NateHeard for clearance)
- [ ] Total Commodities Investment (Use Commodities-E tab in COP20 FAST)
- [ ] Total PEPFAR Investments Ever (Spotlight, make sure to sum only new funding

Important Caveats:
Budget data will be presented only at OU-level
Confirm appropriateness of some data points with SGAC Data Management
Above Site Program Areas may be excluded from analyses
Program Management Program Areas ARE excluded from analyses

**Comment by Yabayabadoo** [comment]
Infographic check-in
PEPFAR Branding Guidance: https://www.state.gov/wp-content/uploads/2019/08/PEPFAR-Branding-Guidance.pdf

**Comment by randyyee** [comment]
Sent 11/13 versions to Botswana Team, awaiting feedback and handoff meeting
